//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public byte ApplicationID { get; set; }
        public string ApplicationName { get; set; }
        public byte AppTypeID { get; set; }
        public Nullable<byte> CriticalityID { get; set; }
        public string ApplicationDescription { get; set; }
        public Nullable<byte> AppServerID { get; set; }
        public Nullable<byte> DBServerID { get; set; }
        public string DBName { get; set; }
        public string AppURL { get; set; }
        public bool ADLinked { get; set; }
        public Nullable<byte> NotesID { get; set; }
        public byte AppStatusID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public byte CreatedByUserID { get; set; }
        public Nullable<System.DateTime> DateLastEdited { get; set; }
        public Nullable<byte> EditedByUserID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ApplicationNote ApplicationNote { get; set; }
        public virtual Server Server { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual AppType AppType { get; set; }
        public virtual Criticality Criticality { get; set; }
        public virtual Server Server1 { get; set; }
    }
}
